/**
 * `doorman fix`: turn ONE open check into a patch, or into a refusal that names
 * the decision only a human can make.
 *
 * ── The rule this module exists to enforce ───────────────────────────────────
 *
 * A fix may change the PROPERTY. It may never change only the text that proves
 * the property.
 *
 * That sounds like a slogan until you read the checks. Eight of the ten pass on
 * evidence a generator could fabricate in one line:
 *
 *   vet-declined-ledger  passes if any rules file matches /declined|deprecated/
 *   mem-handoff          passes if CLAUDE.md says HANDOFF and a command file
 *                        matches /handoff|resume|session/
 *   evidence-convention  passes if CLAUDE.md names an append-only log
 *
 * So a helpful scaffold that wrote `## Declined\n\n(none yet)` into a rules file
 * would move this repo's tool-vetting dimension without recording a single
 * declined tool. The score would rise and the harness would be identical. That
 * is not a fix, it is teaching to the test, and the grade is the product: a
 * grader shipping a tool that games it is worth less than no tool at all.
 *
 * Hence the two classes below, and hence the fact that only ONE check is in the
 * first class. That ratio is not a gap in this command. It is what the checks
 * measure: nine of them measure a human decision (which tools does this agent
 * need, which commands do you actually run, what did you reject and why) and a
 * decision is not derivable from the repo that lacks it.
 *
 *   generate  The correct content is a pure function of the repo. Emitting it
 *             cannot be wrong and cannot be gamed, because the content IS the
 *             truth the check is looking for. Exactly one check qualifies.
 *   worklist  Name the files, name the decision, refuse to guess. Where an
 *             existing command already makes the decision recordable, route to
 *             it rather than inventing a second way.
 *
 * ── Never widens capability ──────────────────────────────────────────────────
 *
 * One asymmetry is load-bearing: this may PROPOSE a deny and never an allow.
 * A deny can only remove capability, so a wrong proposal costs a blocked
 * command. An allow grants it, so a wrong proposal is the tool handing out
 * permissions on a guess. Same reasoning as the gate's fail-closed default.
 *
 * Nothing here consults the network and nothing here reads outside the surface.
 */

import { filesUnder, fileAt, parseFrontmatter } from './surface.mjs';
import { agentsOf, GENERATED_MARKER } from './rubric.mjs';

/**
 * The marker that makes a file doorman's to rewrite.
 *
 * `--write` overwrites a file ONLY when it carries this, or when it does not
 * exist yet. Without the marker there is no way to tell a file this command
 * generated last week from one the user wrote by hand, and overwriting the
 * second is the most expensive mistake available here.
 */
export const MARKER_TAG = GENERATED_MARKER;

/** Paths `--write` refuses outright, whatever the marker says. */
export const NEVER_WRITE = [
  '.claude/settings.json',
  '.claude/settings.local.json',
  '.mcp.json',
];

/**
 * Prefixes `--write` refuses outright.
 *
 * `registry/` is invariant 24: it is the user's trust list, and the gate reads
 * it to decide what runs. `.claude/agents/` because an agent's `tools` line is
 * a security control, and a control this command guessed is worse than a
 * missing one that is visibly missing.
 */
export const NEVER_WRITE_PREFIX = ['registry/', '.claude/agents/'];

/**
 * May `--write` put `content` at `rel`?
 *
 * @param rel      repo-relative path
 * @param existing the file's current raw text, or null when absent
 */
export function writable(rel, existing) {
  if (NEVER_WRITE.includes(rel)) {
    return { ok: false, why: `${rel} is never written by doorman: it is yours, and merging it on a guess clobbers a config` };
  }
  const bad = NEVER_WRITE_PREFIX.find((p) => rel.startsWith(p));
  if (bad) {
    return { ok: false, why: `${rel} is under ${bad}, which doorman never writes` };
  }
  if (existing === null || existing === undefined) return { ok: true, why: 'new file' };
  if (existing.includes(MARKER_TAG)) return { ok: true, why: 'previously generated by doorman' };
  return { ok: false, why: `${rel} exists and carries no ${MARKER_TAG} marker, so it was hand-written` };
}

/* ── generate ──────────────────────────────────────────────────────────────── */

const cell = (s) => String(s ?? '').replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();

const clip = (s, n = 110) => (s.length > n ? s.slice(0, n - 1).trimEnd() + '...' : s);

function unitsOf(surface, prefix) {
  return filesUnder(surface, prefix).map((f) => {
    const fm = parseFrontmatter(f.raw) ?? {};
    return {
      name: f.path.split('/').pop().replace(/\.md$/, ''),
      desc: clip(cell(fm.description)),
      path: f.path,
    };
  });
}

/**
 * The registry, generated from the files themselves.
 *
 * This is the one fix that cannot be gamed. `reg-drift` asks whether every
 * agent and command on disk is named in a doc; the content below IS the list of
 * agents and commands on disk. There is no version of this that satisfies the
 * check while leaving the property false.
 */
export function regDriftContent(surface, { id = 'reg-drift' } = {}) {
  const agents = unitsOf(surface, '.claude/agents/');
  const commands = unitsOf(surface, '.claude/commands/');

  const L = [];
  L.push(`<!-- ${MARKER_TAG} by \`doorman fix ${id}\`. Regenerate after adding or removing`);
  L.push('     an agent or a command. Do not edit the table by hand: a hand-kept list drifts');
  L.push('     in both directions, naming files that were deleted and missing files nobody');
  L.push('     documented. -->');
  L.push('');
  L.push('# Registry: agents and commands');
  L.push('');
  L.push('Every agent and command on disk, read off the filesystem rather than kept by hand.');
  L.push('Descriptions come from the frontmatter of each file, so a stale description here is');
  L.push('a stale description there.');
  L.push('');

  for (const [title, rows, dir] of [
    ['Agents', agents, '.claude/agents/'],
    ['Commands', commands, '.claude/commands/'],
  ]) {
    L.push(`## ${title} (${rows.length})`);
    L.push('');
    if (!rows.length) {
      L.push(`None on disk under \`${dir}\`.`);
      L.push('');
      continue;
    }
    L.push(`| ${title.replace(/s$/, '')} | What it does |`);
    L.push('|---|---|');
    for (const r of rows) L.push(`| \`${r.name}\` | ${r.desc || '_no description in frontmatter_'} |`);
    L.push('');
  }

  L.push(`**${agents.length} agent(s), ${commands.length} command(s).**`);
  return L.join('\n') + '\n';
}

/* ── worklist ──────────────────────────────────────────────────────────────── */

/**
 * A deny list doorman is willing to propose, because every entry only ever
 * REMOVES capability. Printed for review, never written: `.claude/settings.json`
 * is on NEVER_WRITE.
 */
export const PROPOSED_DENY = [
  'Bash(rm -rf *)',
  'Bash(curl * | bash)',
  'Bash(wget * | bash)',
  'Bash(* | sh)',
  'Bash(git push --force*)',
  'Bash(npm publish*)',
  'Write(**/.env)',
  'Write(**/.env.*)',
  'Write(**/.ssh/**)',
  'Write(**/secrets/**)',
];

const settingsTarget = (surface) =>
  fileAt(surface, '.claude/settings.json') ? '.claude/settings.json'
    : fileAt(surface, '.claude/settings.local.json') ? '.claude/settings.local.json'
      : '.claude/settings.json';

/** Each worklist fixer returns targets (real paths) and steps (the decision). */
const WORKLIST = {
  'perm-explicit': (s) => ({
    targets: [settingsTarget(s)],
    steps: [
      'Add a `permissions` block with BOTH `allow` and `deny`. One side alone states half a policy.',
      'The allow list is yours: it has to name the commands you actually run, and doorman cannot know those.',
      'The deny list is not a judgement call. The entries below only ever remove capability, so they are proposed rather than left to you:',
      ...PROPOSED_DENY.map((d) => `    ${d}`),
    ],
    refusal: 'doorman never writes a settings file. Merging one on a guess clobbers a config, and an allow entry it invented would be a permission granted by a tool.',
  }),

  'perm-bash-wildcard': (s) => {
    const files = ['.claude/settings.json', '.claude/settings.local.json']
      .map((p) => fileAt(s, p)).filter(Boolean);
    const bad = [];
    for (const f of files) {
      for (const rule of f.json?.permissions?.allow ?? []) {
        const r = String(rule);
        if (r === 'Bash' || /^Bash\(\s*\*\s*\)$/.test(r) || /^Bash\(\*/.test(r)) bad.push({ path: f.path, rule: r });
      }
    }
    return {
      targets: [...new Set(bad.map((b) => b.path))],
      steps: [
        bad.length
          ? `Remove ${bad.length} unscoped entr${bad.length === 1 ? 'y' : 'ies'}: ${[...new Set(bad.map((b) => b.rule))].join(', ')}`
          : 'No unscoped entry found in a readable settings file.',
        'Replace each with the specific commands you run, scoped: `Bash(git status:*)`, `Bash(npm test:*)`.',
        'Which commands those are is a fact about your workflow, not about your repo, so doorman will not guess it.',
      ],
      refusal: 'Narrowing a wildcard means naming what replaces it. Guessing that list would either break your session or leave the wildcard in place under a longer name.',
    };
  },

  'gate-tools-declared': (s) => {
    const undeclared = agentsOf(s).filter((a) => !a.declaresTools);
    return {
      targets: undeclared.map((a) => a.file.path),
      steps: [
        `${undeclared.length} agent(s) declare no \`tools\` field, so each inherits whatever the parent session holds.`,
        'Add `tools:` to the frontmatter of each file above, listing the minimum that agent needs.',
        'A reviewer needs Read, Grep, Glob. It does not need Write. That minimum is a judgement about what the agent is for, and doorman inventing it would be inventing a security control.',
      ],
      refusal: 'A guessed tool list is a fabricated control. Invariant 9: never fabricate. A missing declaration is visibly missing; a wrong one looks exactly like a right one.',
    };
  },

  'gate-write-declared': (s) => {
    const writers = agentsOf(s).filter((a) => a.canWrite === true || a.canWrite === null);
    return {
      targets: writers.map((a) => a.file.path),
      steps: [
        `${writers.length} agent(s) can write, or declare nothing and therefore might.`,
        'Say in each file what it is allowed to write, and where that is enforced.',
        'Documented-in-a-dispatch-table counts here; it does not count for par-shared-writer, which is about two of them running at once.',
      ],
      refusal: 'What an agent may write is a scope decision. Doorman can list the agents; it cannot decide their scope.',
    };
  },

  'evidence-convention': (s) => ({
    targets: ['CLAUDE.md', '.claude/commands/'],
    steps: [
      'Add a session-end or checkpoint command that APPENDS to one log. One file, one owner, appended and never rewritten.',
      'Name that log in CLAUDE.md so an agent knows to read and write it.',
      'Doorman will not scaffold this: writing the words "append-only log" into CLAUDE.md passes the check with no log behind it.',
    ],
    refusal: 'This check reads CLAUDE.md for a named convention. Generating the sentence without the command behind it would raise the score and change nothing.',
  }),

  'vet-registry': (s) => {
    const mcp = fileAt(s, '.mcp.json');
    const servers = Object.keys(mcp?.json?.mcpServers ?? {});
    const haystacks = [
      ...filesUnder(s, '.claude/rules/'),
      ...(fileAt(s, '.claude/skills/INSTALLED.md') ? [fileAt(s, '.claude/skills/INSTALLED.md')] : []),
      ...(fileAt(s, 'registry/allowlist.json') ? [fileAt(s, 'registry/allowlist.json')] : []),
    ];
    const missing = servers.filter((n) => !haystacks.some((h) => h.raw.includes(n)));
    return {
      targets: ['registry/allowlist.json'],
      steps: missing.length
        ? [
          `${missing.length} declared server(s) appear in no registry: ${missing.join(', ')}`,
          'Each one is a decision, and there is already a command that records it:',
          ...missing.map((n) => `    doorman allow ${n}`),
          'That writes the entry with a NULL grade, which is the honest record of a server you chose to run without measuring it. To measure first: `doorman report <server-url>`.',
        ]
        : ['Every declared server already appears in a registry.'],
      refusal: 'doorman never writes registry/ (invariant 24): it is your trust list and the gate reads it to decide what runs. `doorman allow` exists for this and writes one reviewed entry at a time.',
    };
  },

  'vet-declined-ledger': (s) => ({
    targets: [fileAt(s, '.claude/skills/INSTALLED.md') ? '.claude/skills/INSTALLED.md' : '.claude/rules/'],
    steps: [
      'Add a Declined section naming each rejected tool, the date, and one sentence on what disqualified it.',
      'Doorman will not scaffold an empty one. This check passes on the WORD "declined" appearing in a rules file, so a heading reading `## Declined (none yet)` would move your score while recording nothing.',
      'If you have declined nothing yet, this check is honestly failing and should stay failed until you have.',
    ],
    refusal: 'The check looks for the word. A scaffold would satisfy the check and leave the property false, which is the one thing this command must not do.',
  }),

  'par-shared-writer': (s) => {
    const writers = agentsOf(s).filter((a) => a.canWrite === true || a.canWrite === null);
    const unbounded = writers.filter((a) => !a.isolated && !a.fm['allowed-paths']);
    return {
      targets: unbounded.map((a) => a.file.path),
      steps: [
        `${unbounded.length} of ${writers.length} write-capable agent(s) declare neither \`isolation\` nor \`allowed-paths\`, so two runs can interleave on one file.`,
        'Add `isolation: worktree` to each, or `allowed-paths:` naming what it may touch.',
        'Doorman will not add either. `isolation: worktree` changes WHERE an agent writes, so applying it to an agent meant to edit the main tree breaks that agent quietly.',
        'And `allowed-paths` is a declaration: it is enforced by review, not by the harness. Adding it to every agent moves the score without moving the risk.',
      ],
      refusal: 'Both fixes change agent behaviour. One relocates writes, the other is enforced only by a human reading it. Neither is safe to apply on a guess.',
    };
  },

  'mem-handoff': (s) => {
    const claude = fileAt(s, 'CLAUDE.md');
    const cmd = filesUnder(s, '.claude/commands/').find((f) => /handoff|resume|prime|session/i.test(f.path));
    return {
      targets: ['CLAUDE.md', cmd ? cmd.path : '.claude/commands/'],
      steps: [
        claude ? 'CLAUDE.md exists.' : 'No CLAUDE.md: there is nowhere to name the convention.',
        cmd ? `A session command exists (${cmd.path}).` : 'No session or handoff command exists to maintain the file.',
        'Keep ONE handoff file with a single owner, name it in CLAUDE.md as the first thing to read, and have a command rewrite it at session end.',
        'Give it a last-updated stamp, so a stale one is visibly stale rather than quietly wrong.',
      ],
      refusal: 'This check passes on CLAUDE.md naming a handoff plus any session-shaped command file. Both halves are generatable as text and neither would carry state, so generating them is the gaming case.',
    };
  },
};

/** Which class each check falls in. The ratio is the finding, not a gap. */
export const FIX_CLASS = {
  'reg-drift': 'generate',
  ...Object.fromEntries(Object.keys(WORKLIST).map((k) => [k, 'worklist'])),
};

/**
 * Plan the fix for one check.
 *
 * @returns {{ok, id, why?, cls?, state?, note?, card?, file?, targets?, steps?, refusal?}}
 */
export function planFix(surface, grade, id, { cards = [] } = {}) {
  const check = grade.checks.find((c) => c.id === id);
  if (!check) {
    return { ok: false, id, why: `no such check: ${id}. Known: ${grade.checks.map((c) => c.id).sort().join(', ')}` };
  }
  const card = cards.find((c) => c.id === id) ?? null;
  const base = { ok: true, id, cls: FIX_CLASS[id] ?? 'worklist', state: check.state, check, card };

  if (check.state === 'pass') {
    return { ...base, done: true, note: `${id} already passes (${check.receipt ?? 'no receipt'}). Nothing to fix.` };
  }
  if (check.state === 'n/a') {
    return { ...base, done: true, note: `${id} is not applicable here: ${check.note}` };
  }

  if (base.cls === 'generate') {
    return {
      ...base,
      done: false,
      file: { path: '.claude/rules/command-registry.md', content: regDriftContent(surface, { id }) },
      targets: ['.claude/rules/command-registry.md'],
      steps: [],
      refusal: null,
    };
  }

  const w = WORKLIST[id](surface);
  return { ...base, done: false, file: null, ...w };
}
