/**
 * Generate the site's recommender panel from real captured runs.
 *
 *   node scripts/build-sim.mjs
 *
 * Reads evidence/needs-demo/ and rewrites the `presets` object inside
 * site/index.html, between the two marker comments.
 *
 * WHY THIS IS A SCRIPT AND NOT A PASTE. The panel's first version was written
 * by hand against a command that did not exist yet. Every grade in it was
 * correct, checked row by row against GET /feed, and the SHAPE was wrong: it
 * showed a thirteenth need that does not exist, four verdict words the tool
 * cannot emit, and filed the WebZum F under `needs` when it is `watch` that
 * finds it.
 *
 * That is not a typo, it is drift, and pasting a corrected version by hand only
 * resets the clock on it. A page whose entire claim is "we publish what we
 * measured" cannot print output no run ever produced. So the panel is
 * GENERATED, the input is committed beside the output, and a stale panel is now
 * a failing diff rather than an embarrassment somebody spots later.
 *
 * Re-run it after any change to the renderer, the taxonomy, or the feed.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..');
const DEMO = path.join(ROOT, 'evidence', 'needs-demo');
const PAGE = path.join(ROOT, 'site', 'index.html');

const OPEN = '  // <sim-presets> generated by scripts/build-sim.mjs from evidence/needs-demo. Do not hand-edit.';
const CLOSE = '  // </sim-presets>';

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/**
 * Colour the verdict words the tool actually emits, and nothing else.
 *
 * The list is closed on purpose. Highlighting an arbitrary capitalised word is
 * how `HOSTILE HIT` got onto the page in the first place: it looked like a
 * verdict because it was styled like one.
 */
function colour(line) {
  let out = esc(line);
  out = out.replace(/^(UNMET|COVERED)\b/, '<span class="ok">$1</span>');
  out = out.replace(/^(GAP)\b/, '<span class="warn">$1</span>');
  out = out.replace(/^(BLOCKED)\b/, '<span class="bad">$1</span>');
  out = out.replace(/\b(worth-measuring)\b/g, '<span class="ok">$1</span>');
  out = out.replace(/\b(ungraded)\b/g, '<span class="warn">$1</span>');
  out = out.replace(/\b(blocked|already-installed)\b/g, '<span class="bad">$1</span>');
  return out;
}

function read(file) {
  const full = path.join(DEMO, file);
  if (!fs.existsSync(full)) {
    console.error(`build-sim: missing capture ${file}. Re-run the command and commit its output.`);
    process.exitCode = 2;
    throw new Error('missing capture');
  }
  return fs.readFileSync(full, 'utf8').replace(/\r\n/g, '\n').trimEnd();
}

/** The prompts a capture was run against, read from the committed history. */
function prompts(file) {
  return read(file).split('\n').filter(Boolean).map((l) => JSON.parse(l).message.content);
}

/**
 * `watch --all` prints every graded row, which is 114 lines and the wrong size
 * for a panel. The excerpt is the BLOCKED section and its header, and the panel
 * says it is an excerpt and links the full capture. Trimming for display is
 * fine; trimming an audit transcript is not, and that rule lives in invariant 5
 * where it belongs.
 */
function blockedExcerpt() {
  const lines = read('watch-blocked.txt').split('\n');
  const head = lines.slice(0, 3);
  const at = lines.findIndex((l) => l.startsWith('BLOCKED'));
  if (at < 0) {
    console.error('build-sim: watch-blocked.txt has no BLOCKED section. Re-capture it.');
    process.exitCode = 2;
    throw new Error('no blocked section');
  }
  const end = lines.findIndex((l, i) => i > at && /^[A-Z]/.test(l) && !l.startsWith('BLOCKED'));
  return [...head, '', ...lines.slice(at, end < 0 ? lines.length : end),
    '', '(excerpt. Full run: evidence/needs-demo/watch-blocked.txt)'].join('\n');
}

const PRESETS = [
  ['fullstack', prompts('history-fullstack.jsonl'), read('fullstack.txt'), 'doorman needs .'],
  ['research', prompts('history-research.jsonl'), read('research.txt'), 'doorman needs .'],
  // Deliberately a DIFFERENT command. `needs` matches capability text and
  // WebZum's feed row is a name and a url, so `needs` does not find it and the
  // panel must not pretend otherwise. `watch` does, and prints the tape.
  ['blocked', ['(no prompt history needed: this is doorman watch, which reads the feed)'],
    blockedExcerpt(), 'doorman watch --all'],
];

const js = PRESETS.map(([name, ps, body, cmd]) => {
  const promptJson = ps.map((p) => JSON.stringify(p)).join(',\n        ');
  const termJson = body.split('\n').map((l) => JSON.stringify(colour(l))).join(' + "\\n" +\n        ');
  return `    ${name}: {
      cmd: ${JSON.stringify(cmd)},
      prompts: [
        ${promptJson}
      ],
      terminal:
        ${termJson}
    }`;
}).join(',\n');

const page = fs.readFileSync(PAGE, 'utf8');
const nl = page.includes('\r\n') ? '\r\n' : '\n';
const flat = page.replace(/\r\n/g, '\n');

const from = flat.indexOf(OPEN);
const to = flat.indexOf(CLOSE);
if (from < 0 || to < 0 || to < from) {
  console.error('build-sim: markers not found in site/index.html.');
  console.error(`Expected a line ${OPEN.trim()} and a later ${CLOSE.trim()}`);
  process.exitCode = 2;
  throw new Error('markers missing');
}

const next = flat.slice(0, from + OPEN.length) + '\n  var presets = {\n' + js + '\n  };\n' + flat.slice(to);
fs.writeFileSync(PAGE, next.replace(/\n/g, nl), 'utf8');

console.log(`site/index.html  sim presets regenerated from evidence/needs-demo`);
for (const [name, ps, body] of PRESETS) {
  console.log(`  ${name.padEnd(10)} ${ps.length} prompts, ${body.split('\n').length} lines of real output`);
}
