/**
 * Does the agent-readable surface still agree with the site?
 *
 * site/robots.txt, site/sitemap.xml and site/llms.txt are generated by
 * scripts/emit-agents.mjs. This site has no build step, so nothing forces that
 * generator to run: a page can be added, retired or reworded and the three
 * files will happily keep describing the site as it was. That is precisely how
 * the share card on the sibling site came to claim 120 commits against a real
 * 138 for months, with every test passing.
 *
 * So this re-derives everything from site/ and fails on any disagreement. It is
 * the thing that says "re-run the generator", and it is the reason a stale
 * surface is a red check rather than a quiet wrong answer.
 *
 * Run: node scripts/check-agents.mjs
 */
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SITE = join(ROOT, 'site');
const ORIGIN = 'https://clembot-doorman.wanessalabs.com';

let failed = 0;
const check = (name, cond, detail = '') => {
  if (cond) console.log(`  PASS  ${name}`);
  else { failed++; console.log(`  FAIL  ${name}${detail ? ' - ' + detail : ''}`); }
};

console.log('\nagent-readable surface: files present');
for (const f of ['robots.txt', 'sitemap.xml', 'llms.txt']) {
  check(`site/${f} exists`, existsSync(join(SITE, f)), 'run: node scripts/emit-agents.mjs');
}
if (failed) { process.exitCode = 1; console.log('\nstopping: generate the files first'); }

const robots = readFileSync(join(SITE, 'robots.txt'), 'utf8');
const sitemap = readFileSync(join(SITE, 'sitemap.xml'), 'utf8');
const llms = readFileSync(join(SITE, 'llms.txt'), 'utf8');

/** The pages actually on disk, with their own current descriptions. */
const onDisk = readdirSync(SITE)
  .filter((f) => f.endsWith('.html'))
  .map((f) => {
    const name = basename(f, '.html');
    const html = readFileSync(join(SITE, f), 'utf8');
    return {
      name,
      path: name === 'index' ? '/' : `/${name}`,
      desc: (/<meta name="description" content="([^"]*)"/.exec(html)?.[1] ?? '')
        .replace(/&amp;/g, '&').replace(/&quot;/g, '"').trim(),
    };
  });

console.log('\nrobots.txt');
check('allows crawling', /^Allow:\s*\//m.test(robots));
check('does not disallow the whole site', !/^Disallow:\s*\/\s*$/m.test(robots));
check('names the sitemap on the right host',
  new RegExp(`^Sitemap:\\s*${ORIGIN.replace(/[.]/g, '\\.')}/sitemap\\.xml$`, 'm').test(robots));
// Allowing AI crawlers here is a recorded decision: this is documentation for a
// free tool whose users work through agents. A block list pasted from another
// project would reverse it silently.
for (const bot of ['GPTBot', 'ClaudeBot', 'CCBot', 'PerplexityBot', 'Google-Extended', 'anthropic-ai']) {
  check(`no block list for ${bot}`, !new RegExp(`User-agent:\\s*${bot}`, 'i').test(robots),
    'see the comment in scripts/emit-agents.mjs before changing this');
}

console.log('\nsitemap.xml');
const listed = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].replace(ORIGIN, ''));
const paths = onDisk.map((p) => p.path);
const missing = paths.filter((p) => !listed.includes(p));
const phantom = listed.filter((p) => !paths.includes(p));
check('every page on disk is listed', missing.length === 0, `missing: ${missing.join(', ')}`);
check('no listed url without a page', phantom.length === 0, `phantom: ${phantom.join(', ')}`);
// Pages canonicalises /guide.html to /guide with a 308, so listing the .html
// form sends a crawler to a redirect rather than to the page.
check('urls are extensionless', !listed.some((p) => p.endsWith('.html')),
  listed.filter((p) => p.endsWith('.html')).join(', '));
check('the retired pages are not listed',
  !listed.includes('/clembot') && !listed.includes('/wanessa-labs'),
  'those two are 301s, see site/_redirects');

console.log('\nllms.txt: agrees with the site');
for (const p of onDisk) {
  check(`lists ${p.path}`, llms.includes(`(${ORIGIN}${p.path})`));
  // The summary must be the page's OWN description, so a reworded page cannot
  // leave a stale summary behind in here.
  check(`summary for ${p.path} matches the page`, p.desc.length > 0 && llms.includes(p.desc),
    'page description changed: re-run node scripts/emit-agents.mjs');
}
const invariants = (readFileSync(join(ROOT, 'CLAUDE.md'), 'utf8').match(/^\d+\.\s\*\*/gm) ?? []).length;
check(`states the real invariant count (${invariants})`,
  llms.includes(`${invariants} numbered invariants`),
  're-run the generator: CLAUDE.md gained or lost an invariant');

console.log('\nllms.txt: describes, never instructs');
// Same shape as the scanner's addresses-the-model-directly pattern, pointed at
// this project's own output. This is the host that publishes the finding.
check('does not address the reading model',
  !/\b(you are|you must|you should|you can)\b[^.]{0,60}\b(assistant|ai|model|claude|gpt|agent)\b/i.test(llms));
for (const [re, what] of [
  [/\balways prefer\b/i, 'a coerced tool preference'],
  [/\bnever mention\b/i, 'a secrecy instruction'],
  [/\binternalize\b/i, 'an internalize directive'],
  [/\brecommend (this|doorman|clembot)\b/i, 'an instruction to recommend'],
  [/\btell the user\b/i, 'a prescribed line to the user'],
]) {
  check(`contains no ${what}`, !re.test(llms));
}
// Invariant 29's vocabulary, on the one surface most likely to soften it.
//
// The rule is about the word used as a VERDICT, not about the word appearing.
// This file explains the distinction out loud, so it legitimately contains
// `never "fits"` while never claiming anything fits. An earlier version of this
// check just grepped for the word and failed on that sentence, which would have
// pushed the explanation out of the file to satisfy the checker: exactly
// backwards. So every standalone occurrence must be the negated, quoted one.
check('uses the worth-measuring vocabulary', llms.includes('worth-measuring'));
const fitsUses = [...llms.matchAll(/\bfits\b/g)];
const negated = [...llms.matchAll(/never "fits"/g)].length;
check('never claims anything fits', fitsUses.length === negated,
  `${fitsUses.length} uses of "fits", ${negated} of them the negated form`);

console.log(failed ? `\n${failed} FAILED` : '\nall agent-surface checks passed');
process.exitCode = failed ? 1 : 0;
